import { isWhiteSpace } from "../isWhiteSpace"

test("isWhiteSpace", () => {
	expect(isWhiteSpace("")).toBe(false)
	expect(isWhiteSpace("\u0009")).toBe(true)
	expect(isWhiteSpace("\u0020")).toBe(true)
	expect(isWhiteSpace("\u00a0")).toBe(true)
	expect(isWhiteSpace("\u1680")).toBe(true)
	expect(isWhiteSpace("\u180e")).toBe(true)
	expect(isWhiteSpace("\u2000")).toBe(true)
	expect(isWhiteSpace("\u2001")).toBe(true)
	expect(isWhiteSpace("\u2002")).toBe(true)
	expect(isWhiteSpace("\u2003")).toBe(true)
	expect(isWhiteSpace("\u2004")).toBe(true)
	expect(isWhiteSpace("\u2005")).toBe(true)
	expect(isWhiteSpace("\u2006")).toBe(true)
	expect(isWhiteSpace("\u2007")).toBe(true)
	expect(isWhiteSpace("\u2008")).toBe(true)
	expect(isWhiteSpace("\u2009")).toBe(true)
	expect(isWhiteSpace("\u200a")).toBe(true)
	expect(isWhiteSpace("\u202f")).toBe(true)
	expect(isWhiteSpace("\u205f")).toBe(true)
	expect(isWhiteSpace("\u3000")).toBe(true)
	expect(isWhiteSpace("\u000a")).toBe(true)
	expect(isWhiteSpace("\u000b")).toBe(true)
	expect(isWhiteSpace("\u000c")).toBe(true)
	expect(isWhiteSpace("\u000d")).toBe(true)
	expect(isWhiteSpace("\u0085")).toBe(true)
	expect(isWhiteSpace("\u2028")).toBe(true)
	expect(isWhiteSpace("\u2029")).toBe(true)
})
