import * as _test from "../test"

test("email address", () => {
	expect(_test.emailAddress("")).toBe(false)
	expect(_test.emailAddress("a")).toBe(false)
	expect(_test.emailAddress("a@c")).toBe(false)
	expect(_test.emailAddress("a@c.c")).toBe(true)
	expect(_test.emailAddress("a@c.c.c")).toBe(true)
	expect(_test.emailAddress("a.a@c.c.c")).toBe(true)
	expect(_test.emailAddress("a.a.a@c.c.c")).toBe(true)
	expect(_test.emailAddress("a.a.a+b@c.c.c")).toBe(true)
	expect(_test.emailAddress("a.a.a+b+b@c.c.c")).toBe(true)
	expect(_test.emailAddress("a.a.a+b+b+b@c.c.c")).toBe(true)
})

test("username", () => {
	expect(_test.username("")).toBe(false)
	expect(_test.username("username")).toBe(true)
	expect(_test.username("username1")).toBe(true)
	expect(_test.username("Username1")).toBe(true)
	expect(_test.username("Username1!")).toBe(false)
	expect(_test.username("u53rn4m31")).toBe(true)
	expect(_test.username("u53rn4m31")).toBe(true)
	expect(_test.username("U53rn4m31")).toBe(true)
	expect(_test.username("U53rn4m31!")).toBe(false)
	expect(_test.username("user.name")).toBe(false)
	expect(_test.username("user.name1")).toBe(false)
	expect(_test.username("User.name1")).toBe(false)
	expect(_test.username("User.name1!")).toBe(false)
	expect(_test.username("u53r.n4m31")).toBe(false)
	expect(_test.username("u53r.n4m31")).toBe(false)
	expect(_test.username("U53r.n4m31")).toBe(false)
	expect(_test.username("U53r.n4m31!")).toBe(false)
})

test("password", () => {
	expect(_test.password("")).toBe(false)
	expect(_test.password("password")).toBe(false)
	expect(_test.password("password1")).toBe(false)
	expect(_test.password("Password1")).toBe(true)
	expect(_test.password("Password1!")).toBe(true)
	expect(_test.password("p455w0rd")).toBe(false)
	expect(_test.password("p455w0rd1")).toBe(false)
	expect(_test.password("P455w0rd1")).toBe(true)
	expect(_test.password("P455w0rd1!")).toBe(true)
	expect(_test.password("pass.word")).toBe(false)
	expect(_test.password("pass.word1")).toBe(false)
	expect(_test.password("Pass.word1")).toBe(true)
	expect(_test.password("Pass.word1!")).toBe(true)
	expect(_test.password("p455.w0rd")).toBe(false)
	expect(_test.password("p455.w0rd1")).toBe(false)
	expect(_test.password("P455.w0rd1")).toBe(true)
	expect(_test.password("P455.w0rd1!")).toBe(true)
})
