import hasDistinctValues from "../hasDistinctValues"

test("integration", () => {
	expect(hasDistinctValues([])).toBe(true)
	expect(hasDistinctValues([0])).toBe(true)
	expect(hasDistinctValues([1])).toBe(true)
	expect(hasDistinctValues([2])).toBe(true)
	expect(hasDistinctValues([0, 0])).toBe(false)
	expect(hasDistinctValues([0, 1])).toBe(true)
	expect(hasDistinctValues([0, 2])).toBe(true)
	expect(hasDistinctValues([1, 0])).toBe(true)
	expect(hasDistinctValues([1, 1])).toBe(false)
	expect(hasDistinctValues([1, 2])).toBe(true)
	expect(hasDistinctValues([2, 0])).toBe(true)
	expect(hasDistinctValues([2, 1])).toBe(true)
	expect(hasDistinctValues([2, 2])).toBe(false)
	expect(hasDistinctValues([0, 0, 0])).toBe(false)
	expect(hasDistinctValues([0, 0, 1])).toBe(false)
	expect(hasDistinctValues([0, 0, 2])).toBe(false)
	expect(hasDistinctValues([0, 1, 0])).toBe(false)
	expect(hasDistinctValues([0, 1, 1])).toBe(false)
	expect(hasDistinctValues([0, 1, 2])).toBe(true)
	expect(hasDistinctValues([0, 2, 0])).toBe(false)
	expect(hasDistinctValues([0, 2, 1])).toBe(true)
	expect(hasDistinctValues([0, 2, 2])).toBe(false)
	expect(hasDistinctValues([1, 0, 0])).toBe(false)
	expect(hasDistinctValues([1, 0, 1])).toBe(false)
	expect(hasDistinctValues([1, 0, 2])).toBe(true)
	expect(hasDistinctValues([1, 1, 0])).toBe(false)
	expect(hasDistinctValues([1, 1, 1])).toBe(false)
	expect(hasDistinctValues([1, 1, 2])).toBe(false)
	expect(hasDistinctValues([1, 2, 0])).toBe(true)
	expect(hasDistinctValues([1, 2, 1])).toBe(false)
	expect(hasDistinctValues([1, 2, 2])).toBe(false)
	expect(hasDistinctValues([2, 2, 2])).toBe(false)
})
