import * as ppt from "./playwright"

let page = null
let done = null

beforeAll(async () => {
	jest.setTimeout(600e3)
	const browserStr = process.env.BROWSER
	;[page, done] = await ppt.openPage(browserStr, "http://localhost:3000/demo")
})

afterAll(async () => {
	await done()
})

test("can type and delete words", async () => {
	await ppt.clear(page)
	await ppt.type(page, "Hello, world! 😀\n\nHello, world! 😀\n\nHello, world! 😀")
	let data = await ppt.innerText(page)
	expect(data).toBe("Hello, world! 😀\n\nHello, world! 😀\n\nHello, world! 😀")
	await ppt.backspaceWord(page)
	data = await ppt.innerText(page)
	expect(data).toBe("Hello, world! 😀\n\nHello, world! 😀\n\nHello, world! ")
	await ppt.backspaceWord(page)
	data = await ppt.innerText(page)
	expect(data).toBe("Hello, world! 😀\n\nHello, world! 😀\n\nHello, world")
	await ppt.backspaceWord(page)
	data = await ppt.innerText(page)
	expect(data).toBe("Hello, world! 😀\n\nHello, world! 😀\n\nHello, ")
	await ppt.backspaceWord(page)
	data = await ppt.innerText(page)
	expect(data).toBe("Hello, world! 😀\n\nHello, world! 😀\n\nHello")
	await ppt.backspaceWord(page)
	data = await ppt.innerText(page)
	expect(data).toBe("Hello, world! 😀\n\nHello, world! 😀\n\n")
	await ppt.backspaceWord(page)
	data = await ppt.innerText(page)
	expect(data).toBe("Hello, world! 😀\n\nHello, world! 😀\n")
	await ppt.backspaceWord(page)
	data = await ppt.innerText(page)
	expect(data).toBe("Hello, world! 😀\n\nHello, world! 😀")
	await ppt.backspaceWord(page)
	data = await ppt.innerText(page)
	expect(data).toBe("Hello, world! 😀\n\nHello, world! ")
	await ppt.backspaceWord(page)
	data = await ppt.innerText(page)
	expect(data).toBe("Hello, world! 😀\n\nHello, world")
	await ppt.backspaceWord(page)
	data = await ppt.innerText(page)
	expect(data).toBe("Hello, world! 😀\n\nHello, ")
	await ppt.backspaceWord(page)
	data = await ppt.innerText(page)
	expect(data).toBe("Hello, world! 😀\n\nHello")
	await ppt.backspaceWord(page)
	data = await ppt.innerText(page)
	expect(data).toBe("Hello, world! 😀\n\n")
	await ppt.backspaceWord(page)
	data = await ppt.innerText(page)
	expect(data).toBe("Hello, world! 😀\n")
	await ppt.backspaceWord(page)
	data = await ppt.innerText(page)
	expect(data).toBe("Hello, world! 😀")
	await ppt.backspaceWord(page)
	data = await ppt.innerText(page)
	expect(data).toBe("Hello, world! ")
	await ppt.backspaceWord(page)
	data = await ppt.innerText(page)
	expect(data).toBe("Hello, world")
	await ppt.backspaceWord(page)
	data = await ppt.innerText(page)
	expect(data).toBe("Hello, ")
	await ppt.backspaceWord(page)
	data = await ppt.innerText(page)
	expect(data).toBe("Hello")
	await ppt.backspaceWord(page)
	data = await ppt.innerText(page)
	expect(data).toBe("")
})

test("can type and delete (forwards) words", async () => {
	await ppt.clear(page)
	await ppt.type(page, "Hello, world! 😀\n\nHello, world! 😀\n\nHello, world! 😀")
	let data = await ppt.innerText(page)
	expect(data).toBe("Hello, world! 😀\n\nHello, world! 😀\n\nHello, world! 😀")
	for (let index = 0; index < 52; index++) {
		await ppt.press(page, "ArrowLeft")
	}
	await ppt.backspaceWordForwards(page)
	data = await ppt.innerText(page)
	expect(data).toBe(", world! 😀\n\nHello, world! 😀\n\nHello, world! 😀")
	await ppt.backspaceWordForwards(page)
	data = await ppt.innerText(page)
	expect(data).toBe(" world! 😀\n\nHello, world! 😀\n\nHello, world! 😀")
	await ppt.backspaceWordForwards(page)
	data = await ppt.innerText(page)
	expect(data).toBe("! 😀\n\nHello, world! 😀\n\nHello, world! 😀")
	await ppt.backspaceWordForwards(page)
	data = await ppt.innerText(page)
	expect(data).toBe(" 😀\n\nHello, world! 😀\n\nHello, world! 😀")
	await ppt.backspaceWordForwards(page)
	data = await ppt.innerText(page)
	expect(data).toBe("\n\nHello, world! 😀\n\nHello, world! 😀")
	await ppt.backspaceWordForwards(page)
	data = await ppt.innerText(page)
	expect(data).toBe("\nHello, world! 😀\n\nHello, world! 😀")
	await ppt.backspaceWordForwards(page)
	data = await ppt.innerText(page)
	expect(data).toBe("Hello, world! 😀\n\nHello, world! 😀")
	await ppt.backspaceWordForwards(page)
	data = await ppt.innerText(page)
	expect(data).toBe(", world! 😀\n\nHello, world! 😀")
	await ppt.backspaceWordForwards(page)
	data = await ppt.innerText(page)
	expect(data).toBe(" world! 😀\n\nHello, world! 😀")
	await ppt.backspaceWordForwards(page)
	data = await ppt.innerText(page)
	expect(data).toBe("! 😀\n\nHello, world! 😀")
	await ppt.backspaceWordForwards(page)
	data = await ppt.innerText(page)
	expect(data).toBe(" 😀\n\nHello, world! 😀")
	await ppt.backspaceWordForwards(page)
	data = await ppt.innerText(page)
	expect(data).toBe("\n\nHello, world! 😀")
	await ppt.backspaceWordForwards(page)
	data = await ppt.innerText(page)
	expect(data).toBe("\nHello, world! 😀")
	await ppt.backspaceWordForwards(page)
	data = await ppt.innerText(page)
	expect(data).toBe("Hello, world! 😀")
	await ppt.backspaceWordForwards(page)
	data = await ppt.innerText(page)
	expect(data).toBe(", world! 😀")
	await ppt.backspaceWordForwards(page)
	data = await ppt.innerText(page)
	expect(data).toBe(" world! 😀")
	await ppt.backspaceWordForwards(page)
	data = await ppt.innerText(page)
	expect(data).toBe("! 😀")
	await ppt.backspaceWordForwards(page)
	data = await ppt.innerText(page)
	expect(data).toBe(" 😀")
	await ppt.backspaceWordForwards(page)
	data = await ppt.innerText(page)
	expect(data).toBe("")
})
