import { isSyntax } from "../isSyntax.js"

test("isSyntax", () => {
	expect(isSyntax("")).toBe(false)
	expect(isSyntax("#")).toBe(true)
	expect(isSyntax(" ")).toBe(true)
	expect(isSyntax("/")).toBe(true)
	expect(isSyntax(">")).toBe(true)
	expect(isSyntax("$")).toBe(true)
	expect(isSyntax("`")).toBe(true)
	expect(isSyntax("-")).toBe(true)
	expect(isSyntax("0")).toBe(true)
	expect(isSyntax("1")).toBe(true)
	expect(isSyntax("2")).toBe(true)
	expect(isSyntax("3")).toBe(true)
	expect(isSyntax("4")).toBe(true)
	expect(isSyntax("5")).toBe(true)
	expect(isSyntax("6")).toBe(true)
	expect(isSyntax("7")).toBe(true)
	expect(isSyntax("8")).toBe(true)
	expect(isSyntax("9")).toBe(true)
	expect(isSyntax("_")).toBe(true)
	expect(isSyntax("*")).toBe(true)
	expect(isSyntax("!")).toBe(true)
	expect(isSyntax("[")).toBe(true)
	expect(isSyntax("]")).toBe(true)
	expect(isSyntax("(")).toBe(true)
	expect(isSyntax(")")).toBe(true)
})
